void newCanvas()
{
//=========Macro generated from canvas: newCanvas/newCanvas
//=========  (Wed Mar  4 12:15:30 2020) by ROOT version 6.18/04
   TCanvas *newCanvas = new TCanvas("newCanvas", "newCanvas",0,65,800,700);
   newCanvas->SetHighLightColor(2);
   newCanvas->Range(0.5218391,-3.083489,3.050575,26.28307);
   newCanvas->SetFillColor(0);
   newCanvas->SetBorderMode(0);
   newCanvas->SetBorderSize(2);
   newCanvas->SetTickx(1);
   newCanvas->SetTicky(1);
   newCanvas->SetRightMargin(0.02);
   newCanvas->SetTopMargin(0.02);
   newCanvas->SetFrameLineWidth(2);
   newCanvas->SetFrameBorderMode(0);
   newCanvas->SetFrameLineWidth(2);
   newCanvas->SetFrameBorderMode(0);
   
   TH1D *uncorrInvMassKaonSig__1 = new TH1D("uncorrInvMassKaonSig__1"," ",44,0.8,3);
   uncorrInvMassKaonSig__1->SetBinContent(8,1);
   uncorrInvMassKaonSig__1->SetBinContent(9,1);
   uncorrInvMassKaonSig__1->SetBinContent(10,4);
   uncorrInvMassKaonSig__1->SetBinContent(11,6);
   uncorrInvMassKaonSig__1->SetBinContent(12,10);
   uncorrInvMassKaonSig__1->SetBinContent(13,4);
   uncorrInvMassKaonSig__1->SetBinContent(14,9);
   uncorrInvMassKaonSig__1->SetBinContent(15,19);
   uncorrInvMassKaonSig__1->SetBinContent(16,20);
   uncorrInvMassKaonSig__1->SetBinContent(17,13);
   uncorrInvMassKaonSig__1->SetBinContent(18,12);
   uncorrInvMassKaonSig__1->SetBinContent(19,12);
   uncorrInvMassKaonSig__1->SetBinContent(20,4);
   uncorrInvMassKaonSig__1->SetBinContent(21,1);
   uncorrInvMassKaonSig__1->SetEntries(116);
   uncorrInvMassKaonSig__1->SetDirectory(0);
   uncorrInvMassKaonSig__1->SetStats(0);
   uncorrInvMassKaonSig__1->SetLineColor(4);
   uncorrInvMassKaonSig__1->SetMarkerColor(4);
   uncorrInvMassKaonSig__1->SetMarkerStyle(20);
   uncorrInvMassKaonSig__1->GetXaxis()->SetTitle(" m(K^{+}K^{-}) [GeV/c^{2}]");
   uncorrInvMassKaonSig__1->GetXaxis()->SetLabelFont(42);
   uncorrInvMassKaonSig__1->GetXaxis()->SetLabelSize(0.035);
   uncorrInvMassKaonSig__1->GetXaxis()->SetTitleSize(0.045);
   uncorrInvMassKaonSig__1->GetXaxis()->SetTitleOffset(0.9);
   uncorrInvMassKaonSig__1->GetXaxis()->SetTitleFont(42);
   uncorrInvMassKaonSig__1->GetYaxis()->SetTitle(" Number of events");
   uncorrInvMassKaonSig__1->GetYaxis()->SetLabelFont(42);
   uncorrInvMassKaonSig__1->GetYaxis()->SetLabelSize(0.035);
   uncorrInvMassKaonSig__1->GetYaxis()->SetTitleSize(0.045);
   uncorrInvMassKaonSig__1->GetYaxis()->SetTitleOffset(1.3);
   uncorrInvMassKaonSig__1->GetYaxis()->SetTitleFont(42);
   uncorrInvMassKaonSig__1->GetZaxis()->SetLabelFont(42);
   uncorrInvMassKaonSig__1->GetZaxis()->SetLabelSize(0.035);
   uncorrInvMassKaonSig__1->GetZaxis()->SetTitleSize(0.035);
   uncorrInvMassKaonSig__1->GetZaxis()->SetTitleOffset(1);
   uncorrInvMassKaonSig__1->GetZaxis()->SetTitleFont(42);
   uncorrInvMassKaonSig__1->Draw("E");
   
   TPaveText *pt = new TPaveText(0.74,0.8,0.84,0.95,"brNDC");
   pt->SetFillColor(0);
   pt->SetLineWidth(2);
   pt->SetTextFont(42);
   pt->SetTextSize(0.04);
   TText *pt_LaTex = pt->AddText("p + p #rightarrow p + K^{+} K^{-} + p");
   pt_LaTex = pt->AddText("#sqrt{s} = 510 GeV");
   pt_LaTex = pt->AddText("116 Excl. events");
   pt->Draw();
   
   pt = new TPaveText(0.15,0.91,0.22,0.97,"brNDC");
   pt->SetFillColor(0);
   pt->SetLineWidth(2);
   pt->SetTextSize(0.04);
   pt_LaTex = pt->AddText("STAR Internal");
   pt->Draw();
   
   TH1D *uncorrInvMassKaonBcg__2 = new TH1D("uncorrInvMassKaonBcg__2","Uncorrected inv. mass Kaon",44,0.8,3);
   uncorrInvMassKaonBcg__2->SetBinContent(17,1);
   uncorrInvMassKaonBcg__2->SetBinContent(18,1);
   uncorrInvMassKaonBcg__2->SetBinContent(21,1);
   uncorrInvMassKaonBcg__2->SetBinContent(22,1);
   uncorrInvMassKaonBcg__2->SetEntries(4);
   uncorrInvMassKaonBcg__2->SetDirectory(0);
   uncorrInvMassKaonBcg__2->SetStats(0);
   uncorrInvMassKaonBcg__2->SetLineColor(2);
   uncorrInvMassKaonBcg__2->SetMarkerColor(2);
   uncorrInvMassKaonBcg__2->SetMarkerStyle(20);
   uncorrInvMassKaonBcg__2->GetXaxis()->SetLabelFont(42);
   uncorrInvMassKaonBcg__2->GetXaxis()->SetLabelSize(0.035);
   uncorrInvMassKaonBcg__2->GetXaxis()->SetTitleSize(0.035);
   uncorrInvMassKaonBcg__2->GetXaxis()->SetTitleOffset(1);
   uncorrInvMassKaonBcg__2->GetXaxis()->SetTitleFont(42);
   uncorrInvMassKaonBcg__2->GetYaxis()->SetLabelFont(42);
   uncorrInvMassKaonBcg__2->GetYaxis()->SetLabelSize(0.035);
   uncorrInvMassKaonBcg__2->GetYaxis()->SetTitleSize(0.035);
   uncorrInvMassKaonBcg__2->GetYaxis()->SetTitleFont(42);
   uncorrInvMassKaonBcg__2->GetZaxis()->SetLabelFont(42);
   uncorrInvMassKaonBcg__2->GetZaxis()->SetLabelSize(0.035);
   uncorrInvMassKaonBcg__2->GetZaxis()->SetTitleSize(0.035);
   uncorrInvMassKaonBcg__2->GetZaxis()->SetTitleOffset(1);
   uncorrInvMassKaonBcg__2->GetZaxis()->SetTitleFont(42);
   uncorrInvMassKaonBcg__2->Draw("ESAME");
   
   TLegend *leg = new TLegend(0.58,0.7,0.78,0.8,NULL,"brNDC");
   leg->SetBorderSize(0);
   leg->SetTextSize(0.04);
   leg->SetLineColor(1);
   leg->SetLineStyle(1);
   leg->SetLineWidth(2);
   leg->SetFillColor(0);
   leg->SetFillStyle(0);
   TLegendEntry *entry=leg->AddEntry("uncorrInvMassKaonSig","In+El (unlike-sign pairs)","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(4);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   entry=leg->AddEntry("uncorrInvMassKaonBcg","In+El (like-sign pairs)","p");
   entry->SetLineColor(1);
   entry->SetLineStyle(1);
   entry->SetLineWidth(1);
   entry->SetMarkerColor(2);
   entry->SetMarkerStyle(20);
   entry->SetMarkerSize(1);
   entry->SetTextFont(42);
   leg->Draw();
   
   pt = new TPaveText(0.4799497,0.94,0.5200503,0.995,"blNDC");
   pt->SetName("title");
   pt->SetBorderSize(0);
   pt->SetFillColor(0);
   pt->SetFillStyle(0);
   pt->SetLineWidth(2);
   pt->SetTextFont(42);
   pt_LaTex = pt->AddText(" ");
   pt->Draw();
   newCanvas->Modified();
   newCanvas->cd();
   newCanvas->SetSelected(newCanvas);
}
